import { useState } from 'react';
const packages = { basico: { name: 'Básico', price: 50 }, premium: { name: 'Premium', price: 100 }, aventura: { name: 'Aventura completa', price: 140 } };
const extras = [{ id: 'transport', name: 'Transporte incluido', price: 200 }, { id: 'food', name: 'Alimentación completa', price: 150 }, { id: 'equipment', name: 'Equipo para actividades', price: 100 }];
export default function QuoteCalculator() {
  const [attendees, setAttendees] = useState(1); const [packageId, setPackageId] = useState('basico'); const [selectedExtras, setSelectedExtras] = useState([]);
  const total = Math.max(0, Number(attendees) || 0) * packages[packageId].price + selectedExtras.reduce((sum, id) => sum + extras.find((extra) => extra.id === id).price, 0);
  const toggleExtra = (id) => setSelectedExtras((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  return <section className="card" id="cotizacion"><p className="section-label">Planea tu visita</p><h2>Calcula tu cotización</h2><div className="quote-layout"><div className="form-grid"><label>Número de asistentes<input type="number" min="1" value={attendees} onChange={(event) => setAttendees(event.target.value)} /></label><label>Tipo de paquete<select value={packageId} onChange={(event) => setPackageId(event.target.value)}>{Object.entries(packages).map(([id,item]) => <option key={id} value={id}>{item.name} — Q{item.price} por persona</option>)}</select></label><fieldset><legend>Servicios adicionales</legend>{extras.map((extra) => <label className="check-option" key={extra.id}><input type="checkbox" checked={selectedExtras.includes(extra.id)} onChange={() => toggleExtra(extra.id)} /><span>{extra.name}</span><strong>+ Q{extra.price}</strong></label>)}</fieldset></div><aside className="quote-total" aria-live="polite"><span>Total estimado</span><strong>Q{total.toLocaleString('es-GT')}</strong><small>El precio se actualiza automáticamente.</small></aside></div></section>;
}
